//under constructions, save what?

var params = {
  dt: {
    val: 0.05,
    min: 0.01,
    max: 1,
    default:0.05,
    label: "dt",
    minLabel: "0.01",
    maxLabel: "1",
    integer: false,
    visible: true,
  },  t0: {
    val: 0,
    min: -2*Math.PI,
    max: 2* Math.PI,
    default:0,
    label: "t0",
    minLabel: "-PI",
    maxLabel: "PI",
    integer: false,
    visible: true,
  },
  t1: {
    val: 2* Math.PI,
    min: -2*Math.PI,
    max: 4* Math.PI,
    default:2* Math.PI,
    label: "t1",
    minLabel: "-2PI",
    maxLabel: "4PI",
    integer: false,
    visible: true,
  },
  x0: {
    val: -2,
    min: -4,
    max: 4,
    default: -2,
    label: "x0",
    minLabel: "-4",
    maxLabel: "4",
    integer: false,
    visible: true,
  },
  x1: {
    val: 2,
    min: 1,
    max: 4,
    default: 2,
    label: "x1",
    minLabel: "1",
    maxLabel: "4",
    integer: false,
    visible: true,
  },

  functions: {
    f1: "t",
    f2: "t*t",
    f3: "Math.sin(t)",
    visible: false,
  },
  zoomIn: {
    val: 1,
    visible: true,
    min: 0,
    max: 1,
    default: 1,
    label: "zoom",
    minLabel: "out",
    maxLabel: "in",
    integer: true,
    steps: 1,
  },
  grid: {
    val: 1,
    visible: true,
    min: 0,
    max: 1,
    default: 1,
    label: "show grid",
    minLabel: "no",
    maxLabel: "yes",
    integer: true,
    steps: 1,
  }, 

};
