var params = {
  x0: {
    val: -1,
    min: -10,
    max: 0,
    default: -1,
    label: "x0",
    minLabel: "-10",
    maxLabel: "0",
    recalc: true,
    integer: false,
    visible: true,
  },
  x1: {
    val: 1,
    min: 0,
    max: 10,
    default: 1,
    label: "x1",
    minLabel: "0",
    maxLabel: "10",
    recalc: true,
    integer: false,
    visible: true,
  },
  y0: {
    val: -1,
    min: -10,
    max: 0,
    default: -1,
    label: "y0",
    minLabel: "-10",
    maxLabel: "0",
    recalc: true,
    integer: false,
    visible: true,
  },
  y1: {
    val: 1,
    min: 0,
    max: 10,
    default: 1,
    label: "y1",
    minLabel: "0",
    maxLabel: "10",
    recalc: true,
    integer: false,
    visible: true,
  },
  zFact: {
    val: 1,
    min: 0.1,
    max: 1,
    default: 1,
    label: "z factor",
    minLabel: ".1",
    maxLabel: "1",
    recalc: true,
    visible: true,
    integer: false,
    steps: 9
  },
  funcRes: {
    val: 100,
    min: 10,
    max: 100,
    default: 100,
    label: "resolution",
    minLabel: "10",
    maxLabel: "100",
    integer: true,
    recalc: true,
    visible: true,
    movie: true,
  },
  gridRes: {
    val: 10,
    min: 10,
    max: 100,
    default: 10,
    label: "grid",
    minLabel: "10",
    maxLabel: "100",
    integer: true,
    recalc: true,
    visible: true,
    cssClass: "control2",
  },
  funcOpacity: {
    val: 0.1,
    min: 0,
    max: 1,
    steps: 10,
    default: 0.1,
    label: "opacity",
    minLabel: "transparent",
    maxLabel: "opaque",
    integer: false,
    recalc: true,
    visible: true,
    movie: true,
    cssClass: "control2",
  },

  xyAngle: {
    val: -2.8,
    min: -Math.PI,
    max: Math.PI,
    default: -2.8,
    label: "x,y rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
  },
  zyAngle: {
    val: 0.44,
    min: -Math.PI,
    max: Math.PI,
    default: 0.44,
    label: "y,z rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
  },
  zxAngle: {
    val: 0,
    min: -Math.PI,
    max: Math.PI,
    default: 0,
    label: "x,z rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
  },
  scaleFactor: {
    val: 1.6,
    min: .1,
    max: 10,
    steps: 10,
    default: 1.6,
    label: "zoom",
    minLabel: "far",
    maxLabel: "close",
    integer: false,
    recalc: true,
    visible: true,
    cssClass: "control2",
  },
  perspective: {
    val: 1,
    visible: true,
    min: 0,
    max: 1,
    default: 1,
    label: "perspective",
    minLabel: "off",
    maxLabel: "on",
    integer: true,
    steps: 1,
    recalc: true,
    controlType: "checkbox",
    cssClass: "control2",
  },
  
  
  lrpanning: {
    val: 0,
    min: -10,
    max: 10,
    default: 0,
    label: "left right panning",
    minLabel: "not visible",
    maxLabel: "not visible",
    recalc: true,
    integer: true,
    visible: false,
  },    
  udpanning: {
    val: 0,
    min: -10,
    max: 10,
    default: 0,
    label: "up down panning",
    minLabel: "not visible",
    maxLabel: "not visible",
    recalc: true,
    integer: true,
    visible: false,
  },    
  functions: {
    f1: "sqrt(1-x*x-y*y)",
    f2: "-sqrt(1-x*x-y*y)",
    visible: false,
  },
  functionstoplot:{
   val: "sqrt(1-x*x-y*y),-sqrt(1-x*x-y*y)",
   visible: false,
   bookmarkLink: true,
  },
  functionlabel: {
    f1: "f(x,y)=",
    f2: "g(x,y)=",
    visible: false,
  },
  goButton: {
    show: false,
    visible: false,
  },
  bookmarkLink: {
    show: true,
    visible: false,
  }

};

