var params = {
  branches:{
    val:3,
    min:1,
    max:7,
    default:3,
    label:"branches",
    minLabel:"1",
    maxLabel:"7",
    visible: true,
    recalc: true,
    integer: true,
    },
  "initAngle":{
    val:Math.PI/2,
    min:0,
    max:Math.PI,
    default:Math.PI/2,
    label:"trunk angle",
    minLabel:"0",
    maxLabel:"&pi;",
    visible: false,
    },
  "dAngle":{
    val:Math.PI/8,
    min:Math.PI/8,
    max:Math.PI/4,
    default:Math.PI/8,
    label:"branch angle",
    minLabel:"&pi;/8",
    maxLabel:"&pi;/4",
    visible: true,
    },
  "initLen":{
    val:130,
    min:25,
    max:150,
    default:130,
    label:"trunk initial height",
    minLabel:"25",
    maxLabel:"150",
    integer: true,
    visible: false,
    },
  "minLen":{
    val:20,
    min:15,
    max:40,
    default:20,
    label:"branch min length",
    minLabel:"15",
    maxLabel:"40",
    integer: true,
    visible: false,
    },
  "reduction":{
    val:0.8,
    min:0.5,
    max:0.8,
    default:0.8,
    label:"branch length factor",
    minLabel:"0.5",
    maxLabel:"0.8",
    visible: true,
    },
  "initTrunk":{
    val:20,
    min:1,
    max:50,
    default:20,
    label:"trunk initial thickness",
    minLabel:"1",
    maxLabel:"50",
    integer: true,
    visible: false,
    },
  "trunkReduction":{
    val:0.5, 
    min:0.1,
    max:0.9,
    default:0.5,
    label:"trunk to branch thickness",
    minLabel:"0.1",
    maxLabel:"0.9",
    visible: false,
    },
  "minBranch":{
    val:0.1,
    min:0.1,
    max:1,
    default:0.1,
    label:"branch min thickness",
    minLabel:"0.1",
    maxLabel:"1",
    visible: false,
    },
    
  "nTrees":{
    val:1,
    min:1,
    max:10,
    default:1,
    label:"# trees",
    minLabel:"1",
    maxLabel:"10 (forest)",
    integer: true,
    visible: false,
    },

  x0: {
    val: -1,
    min: -10,
    max: 0,
    default: -1,
    label: "x0",
    minLabel: "-10",
    maxLabel: "0",
    recalc: true,
    integer: false,
    visible: false,
  },
  x1: {
    val: 1,
    min: 0,
    max: 10,
    default: 1,
    label: "x1",
    minLabel: "0",
    maxLabel: "10",
    recalc: true,
    integer: false,
    visible: false,
  },
  y0: {
    val: -1,
    min: -10,
    max: 0,
    default: -1,
    label: "y0",
    minLabel: "-10",
    maxLabel: "0",
    recalc: true,
    integer: false,
    visible: false,
  },
  y1: {
    val: 1,
    min: 0,
    max: 10,
    default: 1,
    label: "y1",
    minLabel: "0",
    maxLabel: "10",
    recalc: true,
    integer: false,
    visible: false,
  },
  zFact: {
    val: 1,
    min: 0.1,
    max: 1,
    default: 1,
    label: "z factor",
    minLabel: ".1",
    maxLabel: "1",
    recalc: true,
    visible: true,
    integer: false,
    steps: 9
  },
  gridRes: {
    val: 10,
    min: 10,
    max: 100,
    default: 10,
    label: "grid",
    minLabel: "10",
    maxLabel: "100",
    integer: true,
    recalc: true,
    visible: false,
  },
  scaleFactor: {
    val: .3,
    min: .01,
    max: 2,
    steps: 20,
    default: .3,
    label: "zoom",
    minLabel: "far",
    maxLabel: "close",
    integer: false,
    recalc: true,
    visible: true
  },
  xyAngle: {
    val: -2.8,
    min: -Math.PI,
    max: Math.PI,
    default: -2.8,
    label: "x,y rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
  },
  zyAngle: {
    val: 0.44,
    min: -Math.PI,
    max: Math.PI,
    default: 0.44,
    label: "y,z rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
  },
  zxAngle: {
    val: 0,
    min: -Math.PI,
    max: Math.PI,
    default: 0,
    label: "x,z rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
  },  
  perspective: {
    val: 0,
    visible: true,
    min: 0,
    max: 1,
    default: 0,
    label: "perspective",
    minLabel: "off",
    maxLabel: "on",
    integer: true,
    steps: 1,
    recalc: true,
    controlType: "checkbox",
  }, 
  lrpanning: {
    val: 0,
    min: -10,
    max: 10,
    default: 0,
    label: "left right panning",
    minLabel: "not visible",
    maxLabel: "not visible",
    recalc: true,
    integer: true,
    visible: false,
  },    
  udpanning: {
    val: 0,
    min: -10,
    max: 10,
    default: 0,
    label: "up down panning",
    minLabel: "not visible",
    maxLabel: "not visible",
    recalc: true,
    integer: true,
    visible: false,
  },    
  goButton: {
    show: false,
    visible: false,
  }

};

