var params = {
  branches: {
    val: 3,
    min: 1,
    max: 5,
    default: 3,
    label: "# branches",
    minLabel: "1",
    maxLabel: "5",
    visible: true,
    recalc: true,
    integer: true,
    newtree: true,
    cssClass: "control1",
  },
  "dAngle": {
    val: Math.PI / 8,
    min: Math.PI / 12,
    max: Math.PI / 4,
    default: Math.PI / 8,
    label: "branches angle",
    minLabel: "&pi;/12",
    maxLabel: "&pi;/4",
    visible: true,
    recalc: true,
    newtree: true,
    cssClass: "control1",

  },
  "minLen": {
    val: 0.4,
    min: 0.4,
    max: 1,
    default: 0.4,
    label: "branch min length",
    minLabel: "0.4",
    maxLabel: "1",
    integer: false,
    steps: 15,
    visible: true,
    recalc: true,
    newtree: true,
    cssClass: "control1",

  },
  "reduction": {
    val: 0.8,
    min: 0.5,
    max: 0.9,
    default: 0.9,
    label: "branches reduction",
    minLabel: "0.5",
    maxLabel: "0.9",
    visible: true,
    recalc: true,
    newtree: true,
    cssClass: "control1",

  },
  "initTrunk": {
    val: 5,
    min: 1,
    max: 10,
    default: 5,
    label: "max thickness",
    minLabel: "1",
    maxLabel: "10",
    integer: true,
    visible: true,
    recalc: true,
    newtree: true,
    cssClass: "control1",

  },
  "trunkReduction": {
    val: 0.5,
    min: 0.5,
    max: 0.9,
    default: 0.5,
    label: "reduction",
    minLabel: "0.5",
    maxLabel: "0.9",
    visible: true,
    recalc: true,
    newtree: true,
    steps: 18,
    cssClass: "control1",

  },
  "minBranch": {
    val: 0.1,
    min: 0.1,
    max: 1,
    default: 0.1,
    label: "min thickness",
    minLabel: "0.1",
    maxLabel: "1",
    visible: false,
    newtree: true,
    cssClass: "control1",
  },

  "nTrees": {
    val: 1,
    min: 1,
    max: 10,
    default: 1,
    label: "# trees",
    minLabel: "1",
    maxLabel: "10 (forest)",
    integer: true,
    visible: false,
  },

  x0: {
    val: -1,
    min: -10,
    max: 0,
    default: -1,
    label: "x0",
    minLabel: "-10",
    maxLabel: "0",
    recalc: true,
    integer: false,
    visible: false,
  },
  x1: {
    val: 1,
    min: 0,
    max: 10,
    default: 1,
    label: "x1",
    minLabel: "0",
    maxLabel: "10",
    recalc: true,
    integer: false,
    visible: false,
  },
  y0: {
    val: -1,
    min: -10,
    max: 0,
    default: -1,
    label: "y0",
    minLabel: "-10",
    maxLabel: "0",
    recalc: true,
    integer: false,
    visible: false,
  },
  y1: {
    val: 1,
    min: 0,
    max: 10,
    default: 1,
    label: "y1",
    minLabel: "0",
    maxLabel: "10",
    recalc: true,
    integer: false,
    visible: false,
  },
  gridRes: {
    val: 10,
    min: 10,
    max: 100,
    default: 10,
    label: "grid",
    minLabel: "10",
    maxLabel: "100",
    integer: true,
    recalc: true,
    visible: false,
  },
  xyAngle: {
    val: -2.8,
    min: -Math.PI,
    max: Math.PI,
    default: -2.8,
    label: "x,y rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
    newtree: false,
    cssClass: "control2",
  },
  zyAngle: {
    val: 0.06,
    min: -Math.PI,
    max: Math.PI,
    default: 0.06,
    label: "y,z rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
    newtree: false,
    cssClass: "control2",

  },
  zxAngle: {
    val: 0,
    min: -Math.PI,
    max: Math.PI,
    default: 0,
    label: "x,z rotation",
    minLabel: "-π",
    maxLabel: "+π",
    recalc: true,
    integer: false,
    visible: true,
    movie: true,
    newtree: false,
    cssClass: "control2",

  },
  perspective: {
    val: 0,
    visible: true,
    min: 0,
    max: 1,
    default: 0,
    label: "perspective",
    minLabel: "off",
    maxLabel: "on",
    integer: true,
    steps: 1,
    recalc: true,
    controlType: "checkbox",
    newtree: false,
    cssClass: "control1",

  },
  scaleFactor: {
    val: .2,
    min: 0.1,
    max: 0.5,
    steps: 100,
    default: .2,
    label: "zoom",
    minLabel: "far",
    maxLabel: "close",
    integer: false,
    recalc: true,
    visible: true,
    newtree: false,
    cssClass: "control1",
  },
  showShadow: {
    val: 1,
    visible: true,
    min: 0,
    max: 1,
    default: 1,
    label: "shadow",
    minLabel: "off",
    maxLabel: "on",
    integer: true,
    steps: 1,
    recalc: true,
    controlType: "checkbox",
    newtree: false,
    cssClass: "control2",

  },
  sunHorizonAngle: {
    val: Math.PI/2-.1,
    min: 0,
    max: 2*Math.PI-0.1,
    steps: 24,
    default: Math.PI/2-.1,
    label: "hour",
    minLabel: "sunrise",
    maxLabel: "sunset",
    visible: true,
    recalc: true,
    integer: false,
    newtree: false,
    movie: true,
    cssClass: "control2",

  },//
  sunDirectionAngle: {
    val: 0,
    min: 0,
    max: Math.PI,
    steps: 12,
    default: 0,
    label: "horizon",
    minLabel: "winter",
    maxLabel: "summer",
    visible: true,
    recalc: true,
    integer: false,
    newtree: false,
    movie: true,
    cssClass: "control2",
  },
  axis: {
    val: 1,
    visible: true,
    min: 0,
    max: 1,
    default: 1,
    label: "axis",
    minLabel: "off",
    maxLabel: "on",
    integer: true,
    steps: 1,
    recalc: true,
    controlType: "checkbox",
    newtree: false,
    cssClass: "control1",
  },
  lrpanning: {
    val: 0,
    min: -10,
    max: 10,
    default: 0,
    label: "left right panning",
    minLabel: "not visible",
    maxLabel: "not visible",
    recalc: true,
    integer: true,
    visible: false,
    newtree: false,
  },
  udpanning: {
    val: -2,
    min: -10,
    max: 10,
    default: -2,
    label: "up down panning",
    minLabel: "not visible",
    maxLabel: "not visible",
    recalc: true,
    integer: true,
    visible: false,
    newtree: false,
  },
  goButton: {
    show: false,
    visible: false,
  },
  bookmarkLink: {
    show: true,
    visible: false,
  }

};
